var description = {
	Aquarius: "Aquarius people rebellious, unique, and futuristic. They are commuity based humanitarians. Aquarians are blessed with skills and knowledge way beyond their time and are usually able to convert that knowledge to the betterment of humanity. This makes them great inventors, intellectuals and selfless leaders.",
	Pisces: "Pisces people are dreamy, compassionate, and spiritual. They are the odest sign of the zodiac and kind encompass all of life. The fishes go around and arouns in a circle like yin and yang. Pisceans possess an intuitive and magical understanding of the world that cannot be explained. They make for great religious and spiritual leaders, artists, occultists and peacemakers",
	Aries: "Aries people are confident, brave and bold. Like a spark that is lit from a match, Aries people charge into a situation head-first preferring to act now and think later. They make great leaders because of their individualistic nature.",
	Taurus: "Taurus people are practical, stubborn and tranquill. Like a rock tey refuse to be moved nor move others. They are grounded in their approach to life, making them quite savvy in materialistic pursuits.",
	Gemini: "Gemini people are open-minded, witty and talkative. Like a butterfly, Geminis are had to pin down, hate boredom and flee situations that no longer serve their mercurial interests. They are great conversationalists and communicators",
	Cancer: "Cancer people are empathetic, sensitive and caring; like the crab, they are defensive and wary of new situations. But when they open up, they are quite warm and friendly. Cancers are great nurturers and do their best to make sure that everyone's needs are met.",
	Leo: "Leo people are dynamic, animated and warm. Like the lion, they see themselves as the king in any situation. They have a selfish streak to them, but people don't mind because of their good-natured, generous personality. Leos thrive on attention and the spotlight, so they make great entertainers, CEO's and leaders",
	Virgo: "Virgo people are analytical, logical and intelligent. They have a fine eye for details, which can make them quite critical of themselves and others. They want everything to be perfect. Virgos do keep the world moving forward, though because they make great organizers, workers, healers and helpers.",
	Libra: "Libra people are charming, thoughtful, and selfless. Because they weigh all ideas objectively, they have trouble making decisions. Librans are very concerned with the 'other half.' They want to make sure that all interactions are fair and just. This makes them great lawyers, judges, mediators and counselors",
	Scorpio: "Scorpio people are mysteriouos, deep amd magnetic. Like stagnant pools of water, scorpios hold intense emotions liek monsters lurking beneath. They have a keen ability to read between the lines making them great detectives, spies, occultists and psychologists. Scorpio people cut down to the root of something and discard and destroy whatever is unnecessary, transforming them selves and others in the process.",
	Sagittarius: "Sagittarius people are opinionated, knowledgable and driven. Like an archer, a Sagittarius sees everything from above allowing them to pursue actions and ideas that are most meaningful. Sagittarius is the sign of travel and great wisdom. They make excellent teachers and professors.",
	Capricorn: "Capricorn people are serious, down-to-earth and cautious. Like the goat, they gracefully maneuver their way to the top of the mountain at a slow and steady pace. Capricorns can achieve mastery in just about anything they set their minds to because they understand discipline and hard work better then any other sign."
}
